### ISSUE TITLE
Make a different class for loading images

### ISSUE THREAD

**Issue by slickwilfred** [COMP2522/project-zoom-zoom#104]
https://github.com/COMP2522/project-zoom-zoom/blob/ad095fc8e7d59c956996bc433c27b9aee3578742/Game/src/main/java/project/ControlMenu.java#L74-L86

**Comment by chino0522** [comment]
Instead, I've created a new method that has a return value of 'PImage' which also has a String as a parameter for the file name of the image:

  private PImage getImage(String name) {
    return window.loadImage("Game/images/" + name);
  }
